// src/pages/todo/ContentDefault/components/ContentDefaultItem.vue
<template>
  <div v-if="item" class="content-default-item"
       :class="itemId === item.id ? 'active' : ''"
       :key="item.id" @click.stop>
    <todo-item-checkbox :priority="item.priority" :status="item.status"
                        @click.stop="updateStatus(item.id, item.status)"/>
    <a-dropdown align-point trigger="contextMenu">
      <div class="title" @click="setItemId(item.id)" :style="{color: handleColor(item)}">
        {{ item.title }}
      </div>
      <template #content>
        <a-dsubmenu>
          <template #icon>
            <icon-thunderbolt/>
          </template>
          <span>优先级</span>
          <template #content>
            <content-default-item-doption
              :priority="TodoItemPriority.HIGH"
              @click="updatePriority(item.id, TodoItemPriority.HIGH)" text="高优先级"/>
            <content-default-item-doption
              :priority="TodoItemPriority.MIDDLE"
              @click="updatePriority(item.id, TodoItemPriority.MIDDLE)" text="中优先级"/>
            <content-default-item-doption
              :priority="TodoItemPriority.FLOOR"
              @click="updatePriority(item.id, TodoItemPriority.FLOOR)" text="低优先级"/>
            <content-default-item-doption
              :priority="TodoItemPriority.NONE"
              @click="updatePriority(item.id, TodoItemPriority.NONE)" text="无优先级"/>
          </template>
        </a-dsubmenu>
        <a-doption style="color: rgb(var(--orange-6));" @click="updateStatusToAbandon(item.id)">
          <template #icon>
            <thumb-down-icon />
          </template>
          放弃
        </a-doption>
        <a-doption style="color: rgb(var(--red-6));" @click="removeById(item.id)">
          <template #icon>
            <delete-icon />
          </template>
          删除
        </a-doption>
      </template>
    </a-dropdown>
    <a-tooltip :content="(item.top? '取消': '') + '置顶'" position="right">
      <t-button theme="primary" variant="text" shape="square" :style="{color: item.top ? 'rgb(var(--orange-6))' : 'var(--color-neutral-4)'}"
                @click="updateTop(item.id, !item.top)">
        <template #icon>
          <icon-arrow-rise/>
        </template>
      </t-button>
    </a-tooltip>
  </div>
</template>
<script lang="ts" setup>
import {
  getNextTodoItemStatus,
  handlePriorityColor,
  TodoItemIndex,
  TodoItemPriority,
  TodoItemStatus
} from "@/entity/todo/TodoItem";
import {useTodoWrapStore} from "@/store/components/TodoWrapStore";
import {useGlobalStore} from "@/store/GlobalStore";
import MessageUtil from "@/utils/modal/MessageUtil";
import {useUmami} from "@/plugin/umami";
import {useTodoItemStore} from "@/store/db/TodoItemStore";
import ContentDefaultItemDoption from "@/pages/todo/ContentDefault/components/ContentDefaultItemDoption.vue";
import MessageBoxUtil from "@/utils/modal/MessageBoxUtil";
import {DeleteIcon, ThumbDownIcon} from "tdesign-icons-vue-next";

defineProps({
  item: {
    type: Object as PropType<TodoItemIndex>
  }
});

const itemId = computed(() => useTodoWrapStore().itemId);
const setItemId = (e: number) => useTodoWrapStore().setItemId(e);
const handleColor = (item: TodoItemIndex): string => {
  if (item.status === TodoItemStatus.COMPLETE || item.status === TodoItemStatus.ABANDON) {
    return 'var(--color-text-1)';
  }
  return handlePriorityColor(item.priority);
};

const updateTop = (id: number, top: boolean) => useTodoItemStore().updateById(id, {top})
  .then(() => MessageUtil.success(top ? "已置顶" : "取消置顶"))
  .catch(e => MessageUtil.error((top ? "置顶" : "取消置顶") + "失败", e));

function updateStatus(itemId: number, status: TodoItemStatus) {
  useTodoItemStore().updateById(itemId, {status: getNextTodoItemStatus(status)})
    .then(record => {
      if (record.status === TodoItemStatus.COMPLETE) {
        MessageUtil.success(`【${record.title}】已完成`);
        useUmami.track('/待办/状态/完成');
      } else if (record.status === TodoItemStatus.ABANDON) {
        useUmami.track('待办/状态/放弃');
      }
    })
    .catch(e => MessageUtil.error("更新失败", e));
}

function updatePriority(id: number, priority: TodoItemPriority) {
  useGlobalStore().startLoading("开始更新待办项");
  useTodoItemStore().updateById(id, {priority})
    .then(() => MessageUtil.success("更新成功"))
    .catch(e => MessageUtil.error("更新失败", e))
    .finally(() => useGlobalStore().closeLoading());
}

async function _updateStatusToAbandon(itemId: number): Promise<TodoItemIndex> {
  // 实时查询
  const attr = await useTodoItemStore().getTodoItemAttr(itemId);
  const reason = await MessageBoxUtil.prompt("请输入放弃原因", "放弃待办", {
    confirmButtonText: "放弃",
    cancelButtonText: "取消",
    inputValue: attr.reason
  });
  const record = await useTodoItemStore()
    .updateById(itemId, {status: TodoItemStatus.ABANDON}, {reason})
  return Promise.resolve(record);
}

function updateStatusToAbandon(itemId: number) {
  useGlobalStore().startLoading("开始更新待办项");
  _updateStatusToAbandon(itemId)
    .then(record => {
      if (record.status === TodoItemStatus.COMPLETE) {
        MessageUtil.success(`【${record.title}】已完成`)
      }
    })
    .catch(e => {
      MessageUtil.error("更新失败", e)
    })
    .finally(() => useGlobalStore().closeLoading());
}

function removeById(id: number) {
  MessageBoxUtil.confirm("是否删除该待办项？", "删除提示", {
    confirmButtonText: "删除"
  }).then(() => {
    useGlobalStore().startLoading("开始删除待办项");
    useTodoItemStore().deleteById(id)
      .then(() => MessageUtil.success("删除成功"))
      .catch(e => MessageUtil.error("删除失败", e))
      .finally(() => useGlobalStore().closeLoading());
  })
}
</script>
<style scoped lang="less">
.content-default-item {
  position: relative;
  padding: 4px 7px;
  border-bottom: 1px solid var(--color-neutral-3);
  display: grid;
  grid-template-columns: 30px 1fr 32px;
  height: 32px;
  line-height: 32px;
  cursor: pointer;

  &:last-child {
    border-bottom: 1px solid transparent;
  }

  &:hover {
    background-color: var(--color-fill-3);
  }

  &.active {
    background-color: var(--color-fill-3);
  }

  .extra {
    color: rgb(var(--orange-6));

    &.disabled {
      color: var(--color-neutral-4);
    }
  }

  .gray {
    color: var(--color-neutral-6);
  }

  .delete {
    text-decoration: line-through
  }

  .title {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
}
</style>

// src/pages/todo/ContentDefault/components/ContentDefaultItem.tsx
import ContextMenu from '@imengyu/vue3-context-menu';
import {CheckIcon, DeleteIcon, FlagIcon, ThumbDownIcon} from "tdesign-icons-vue-next";
import {useGlobalStore} from "@/store";
import {handlePriorityColor, TodoItemIndex, TodoItemPriority, TodoItemStatus} from "@/entity/todo/TodoItem";
import {useTodoItemStore} from "@/store/db/TodoItemStore";
import MessageUtil from "@/utils/modal/MessageUtil";
import MessageBoxUtil from "@/utils/modal/MessageBoxUtil";

function updatePriority(id: number, priority: TodoItemPriority) {
  useGlobalStore().startLoading("开始更新待办项");
  useTodoItemStore().updateById(id, {priority})
    .then(() => MessageUtil.success("更新成功"))
    .catch(e => MessageUtil.error("更新失败", e))
    .finally(() => useGlobalStore().closeLoading());
}

async function _updateStatusToAbandon(itemId: number): Promise<TodoItemIndex> {
  // 实时查询
  const attr = await useTodoItemStore().getTodoItemAttr(itemId);
  const reason = await MessageBoxUtil.prompt("请输入放弃原因", "放弃待办", {
    confirmButtonText: "放弃",
    cancelButtonText: "取消",
    inputValue: attr.reason
  });
  const record = await useTodoItemStore()
    .updateById(itemId, {status: TodoItemStatus.ABANDON}, {reason})
  return Promise.resolve(record);
}

function updateStatusToAbandon(itemId: number) {
  useGlobalStore().startLoading("开始更新待办项");
  _updateStatusToAbandon(itemId)
    .then(record => {
      if (record.status === TodoItemStatus.COMPLETE) {
        MessageUtil.success(`【${record.title}】已完成`)
      }
    })
    .catch(e => {
      MessageUtil.error("更新失败", e)
    })
    .finally(() => useGlobalStore().closeLoading());
}

function removeById(id: number) {
  MessageBoxUtil.confirm("是否删除该待办项？", "删除提示", {
    confirmButtonText: "删除"
  }).then(() => {
    useGlobalStore().startLoading("开始删除待办项");
    useTodoItemStore().deleteById(id)
      .then(() => MessageUtil.success("删除成功"))
      .catch(e => MessageUtil.error("删除失败", e))
      .finally(() => useGlobalStore().closeLoading());
  })
}

export function onContentDefaultItem(e: MouseEvent, item: TodoItemIndex) {
  ContextMenu.showContextMenu({
    x: e.x,
    y: e.y,
    theme: useGlobalStore().isDark ? 'default dark' : 'default',
    items: [
      {
        label: '优先级',
        icon: () => <FlagIcon/>,
        children: [{
          label: () => <div style={{color: handlePriorityColor(TodoItemPriority.HIGH)}}>高优先级</div>,
          icon: () => item.priority === TodoItemPriority.HIGH ?
            <CheckIcon style={{color: handlePriorityColor(TodoItemPriority.HIGH)}}/> : <div></div>,
          onClick: () => updatePriority(item.id, TodoItemPriority.HIGH)
        }, {
          label: () => <div style={{color: handlePriorityColor(TodoItemPriority.MIDDLE)}}>中优先级</div>,
          icon: () => item.priority === TodoItemPriority.MIDDLE ?
            <CheckIcon style={{color: handlePriorityColor(TodoItemPriority.MIDDLE)}}/> : <div></div>,
          onClick: () => updatePriority(item.id, TodoItemPriority.MIDDLE)
        }, {
          label: () => <div style={{color: handlePriorityColor(TodoItemPriority.FLOOR)}}>低优先级</div>,
          icon: () => item.priority === TodoItemPriority.FLOOR ?
            <CheckIcon style={{color: handlePriorityColor(TodoItemPriority.FLOOR)}}/> : <div></div>,
          onClick: () => updatePriority(item.id, TodoItemPriority.FLOOR)
        }, {
          label: () => <div style={{color: handlePriorityColor(TodoItemPriority.NONE)}}>无优先级</div>,
          icon: () => item.priority === TodoItemPriority.NONE ?
            <CheckIcon style={{color: handlePriorityColor(TodoItemPriority.NONE)}}/> : <div></div>,
          onClick: () => updatePriority(item.id, TodoItemPriority.NONE)
        }]
      }, {
        label: () => <div style={{color: 'rgb(var(--orange-6))'}}>放弃</div>,
        icon: () => <ThumbDownIcon style={{color: 'rgb(var(--orange-6))'}}/>,
        onClick: () => updateStatusToAbandon(item.id)
      }, {
        label: () => <div style={{color: 'rgb(var(--red-6))'}}>删除</div>,
        icon: () => <DeleteIcon style={{color: 'rgb(var(--red-6))'}}/>,
        onClick: () => removeById(item.id)
      }
    ]
  })
}
